---
- hosts: local
  tasks:
    - name: install docker compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: chmod +x /usr/local/bin/docker-compose
      shell: chmod +x /usr/local/bin/docker-compose
